### ISSUE TITLE
Support Hive 3, in a release

### ISSUE THREAD

**Issue by ches** [klarna/HiveRunner#120]
**Is your feature request related to a problem? Please describe.**

Major Hadoop distributions and cloud platforms are now including Hive 3. HiveRunner is not usable for test projects building with Hive 3 libraries to target deployment to those environments.

**Describe the solution you'd like**

Support for Hive 3 implemented.

@gerlowskija got the ball rolling in #93, which was merged to a `hive-3.x` branch [with the intention to release snapshots from it as further work solidified][1]. It has some utility already in its current state, but needs updates from the two years since, and @massdosage observed some remaining issues:

> I had another look at the `hive-3.x` branch and merged in master and updated to Hive 3.1.2 and some tests have started failing so I haven't pushed that yet. I think this might be expected behaviour due to changes in how Dates and Timestamps are treated in Hive 3 but I haven't had time to look into it properly yet.

This issue can track resolving such problems, and hold discussion about the logistics of releasing and managing the support in the project:

> Once we get that working we can have a discussion about how best to move this project forward so we can support both Hive 2.x and 3.x. My initial thought is to create a hive-2.x branch and keep that for 2.x releases and append a "-hive2" suffix to the artifactId and then use master for Hive 3.x but I'm open to other suggestions.

Considerations that may change defaults or supported options for HiveRunner:

- Tez is the default execution engine and MapReduce is not supported
- Only the Beeline CLI is supported

Other change references that may be useful:

- <https://cwiki.apache.org/confluence/display/Hive/AdminManual+Metastore+3.0+Administration>

[1]: https://github.com/klarna/HiveRunner/pull/93#issuecomment-405661641

**Comment by massdosage** [comment]
OK, I have pushed changes to the `hive-3.x` branch which update it to the latest 3.x version of Hive. This breaks the build and demonstrates things that still need to be sorted out before we would consider a release:

* Fix the broken test `InsertIntoTableIntegrationTest.insertDataIntoTablePrimitiveParsedStrings` - I'm not sure what is causing the ClassCastExceptions here but we should figure out if they are a problem or if the test needs to change.
* `PreV200HiveShellHiveCliEmulationTest` - should we drop support for this pre-Hive 2 CLI emulation? Doesn't look like it's supported by Hive itself in version 3.
* The tests are full of warning messages like "Caused by: java.sql.SQLSyntaxErrorException: Table/View 'TBLS' does not exist." They don't appear to break anything but they look ugly. Is this a side effect of turning on more table validation as part of the move to Hive 3? Can we fix the error or do we need to turn the validation off again?
* As above but for "WARN  DataNucleus.MetaData:96 - Metadata has jdbc-type of null yet this is not valid. Ignored" messages.

**Comment by massdosage** [comment]
HiveRunner 6.0.0 now supports HIve 3.1.2
