### ISSUE TITLE
maven central release

### ISSUE THREAD

**Issue by patduin** [klarna/HiveRunner#9]
Hi,

Have you considered pushing releases to maven central? It will make using hiverunner much easier as we don't have to clone and build a release ourselves?

Kind regards,
 Patrick

**Comment by PelleUllberg** [comment]
Hi, 

Yes that is something we need to do, but have not yet had time to do. I'd welcome any contribution on this :D

/Pelle

**Comment by massdosage** [comment]
We've done this for all our open source projects so would definitely be happy to help. It's a bit of a faff to set up for the first time and the documentation isn't as straightforward as it could be. The main documentation covering what you need to do is here:

https://maven.apache.org/guides/mini/guide-central-repository-upload.html

Hidden towards the bottom of that page is a list of steps you need to do in order to be able to publish to their OSS repo:

http://central.sonatype.org/pages/ossrh-guide.html

Basically you need to create a Jira ticket with them explaining who you are, what the project is etc. Once they approve that you go through the other steps to set up a GPG key and modify your pom to publish to central. You should then be able to release to their Nexus using mvn release:prepare/perform. You still then have to log in to Nexus to promote your release to the repo or you can use a plugin to do this as part of your release like we do (see https://github.com/HotelsDotCom/hotels-oss-parent/blob/master/pom.xml#L168). 

Unfortunately we can't help with too much of the above as you should really be the ones requesting the access and being granted it so that you can do releases. Any questions along the way we're happy to help with.

**Comment by jitpack-io** [comment]
Hi!
In the meantime this might help someone https://jitpack.io/#klarna/HiveRunner/e4865a5956

**Comment by Thoymas** [comment]
We have now released hiverunner to maven central.

**Comment by Thoymas** [comment]
Hiverunner is now released to maven central. Thanks for the helpful references!

**Comment by massdosage** [comment]
Excellent news! This will certainly make our lives easier and will hopefully increase adoption of HiveRunner.

**Comment by massdosage** [comment]
One small point, I see the release you just did is version 2.5.1 so shouldn't the pom now have 2.5.2-SNAPSHOT and not 2.5.1-SNAPSHOT? Looks like something didn't go quite right here...

**Comment by PelleUllberg** [comment]
Could be wrong here because we internally always use the mvn release plugin
so I rarely pay attention, but I think that you bump the version when you
do the release and then continuou with that version on trunk with the
suffix -SNAPSHOT.
This makes sense since you don't really know what to set the next version
to until you do the next release.

/Pelle

**Comment by massdosage** [comment]
Well, the mvn release plugin convention to increment to the next minor release - i.e. 2.5.2-SNAPSHOT. I would recommend sticking to this to avoid confusion as with 2.5.1-SNAPSHOT it looks like the most recent release was 2.5.0 as 2.5.1-SNAPSHOT is usually what you have *before* 2.5.1, not after.

**Comment by PelleUllberg** [comment]
In that case, my bad. Lets fix it.

/Pelle

**Comment by Thoymas** [comment]
Actually, it's my bad. I'll fix it.

**Comment by Thoymas** [comment]
Done.
